# The Site Configuration

theme: jekyll-theme-chirpy

lang: en
timezone: Asia/Kuala_Lumpur

# SEO
title: G10D
tagline: Certified Skills Issued
description: >-
  Cybersecurity student sharing CTF write-ups, lab notes, penetration testing practice,
  reverse engineering challenges, and technical documentation.

url: "https://g10d.github.io"
baseurl: "/g10d.github.io"

github:
  username: 0xG10D

social:
  name: Irfan Shah
  email: irfan.shahrizan310@gmail.com
  fediverse_handle:
  links:
    - https://github.com/0xG10D
    - https://www.linkedin.com/in/irfanshahrizan/

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Analytics
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

# Theme mode: leave empty for system default
theme_mode: dark

# CDN for Chirpy assets
cdn: "https://chirpy-img.netlify.app"

# Sidebar avatar
avatar: "https://i.pinimg.com/736x/54/40/a3/5440a327daebb42adc521d6090a63211.jpg"

# SEO preview image
social_preview_image:

# Posts
toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: en
    reactions_enabled: 1

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
